ERP/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('product_master.urls')),
    path('rest_api/',include('drf.urls')),
    path('user/',include('user_management.urls')),

]

product_master/urls.py
from django.urls import path
from . import views

app_name = 'product_master'

urlpatterns = [
    path('',views.ListProduct.as_view(),name='list_view'),
    path('create_view/',views.CreateProduct.as_view(),name='create_view'),
    path('detail_view/<int:pk>/',views.DetailProduct.as_view(),name='detail_view'),
    path('update_view/<int:id>/',views.UpdateProduct.as_view(),name='update_view'),
    path('delete_view/<int:id>/',views.DeleteProdcut.as_view(),name='delete_view'),

    path('reports_view/',views.GenerateReport.as_view(),name='reports_view'),
]

user_management/urls.py
from django.urls import path
from django.contrib.auth.views import LogoutView,LoginView
from .views import RegisterView

app_name = 'user_management'

urlpatterns = [
    path('login/', LoginView.as_view(template_name='login.html'), name='login'),
    path('register/', RegisterView.as_view(), name='register'),
    path('logout/', LogoutView.as_view(), name='logout'),
]

templates/add_product.html
{% extends 'base.html '%}
{% block content %}
<div class="right_col" role="main">
   <div class="">
      <div class="page-title">
         <div class="title_left">
            <h3>Create New Product</h3>
         </div>
      </div>
      <div class="clearfix"></div>
      <div class="row">
         <div class="col-md-12 col-sm-12 ">
            <div class="x_panel">
               <div class="x_content">
                  <br />
                  <form id="demo-form2" data-parsley-validate class="form-horizontal form-label-left" method="post" action="{% url 'product_master:create_view'%}">
                     {% csrf_token %}
                     <div class="form-group row">
                        <label class="col-form-label col-md-3 col-sm-3 label-align">Select <span class="required">*</span></label>
                        <div class="col-md-6 col-sm-6 ">
                           <select class="form-control" required="required" name="category_id">
                              {% for category in category %}
                              <option value="{{category.id}}">{{category.Category}}</option>
                              {% endfor %}
                           </select>
                        </div>
                     </div>
                     <div class="item form-group">
                        <label class="col-form-label col-md-3 col-sm-3 label-align" for="product-name">Product Name <span class="required">*</span>
                        </label>
                        <div class="col-md-6 col-sm-6 ">
                           <input type="text" id="product-name" name="name" required="required" class="form-control ">
                        </div>
                     </div>
                     <div class="item form-group">
                        <label class="col-form-label col-md-3 col-sm-3 label-align" for="quantity">Quantity<span class="required">*</span>
                        </label>
                        <div class="col-md-6 col-sm-6 ">
                           <input type="text" id="quantity" name="quantity" required="required" class="form-control">
                        </div>
                     </div>
                     <div class="item form-group">
                        <label for="description" class="col-form-label col-md-3 col-sm-3 label-align">Description</label>
                        <div class="col-md-6 col-sm-6 ">
                           <input id="description" name="description" class="form-control" type="text" name="description">
                        </div>
                     </div>
                     <div class="item form-group">
                        <label for="amount" class="col-form-label col-md-3 col-sm-3 label-align">Price</label>
                        <div class="col-md-6 col-sm-6 ">
                           <input id="amount" class="form-control" required="required" type="text" name="amount">
                        </div>
                     </div>
                     <div class="item form-group">
                        <label class="col-form-label col-md-3 col-sm-3 label-align">Created Date <span class="required">*</span>
                        </label>
                        <div class="col-md-6 col-sm-6 ">
                           <input id="birthday" name="created_date" class="date-picker form-control" placeholder="dd-mm-yyyy" type="text" required="required" type="text" onfocus="this.type='date'" onmouseover="this.type='date'" onclick="this.type='date'" onblur="this.type='text'">
                           <script>
                          
                              // Function to format date as yyyy-mm-dd
                              function formatDate(date) {
                                  var d = new Date(date),
                                      month = '' + (d.getMonth() + 1),
                                      day = '' + d.getDate(),
                                      year = d.getFullYear();
                              
                                  if (month.length < 2) month = '0' + month;
                                  if (day.length < 2) day = '0' + day;
                              
                                  return [year, month, day].join('-');
                              }
                              
                              // Set the current date as the default value
                              document.addEventListener('DOMContentLoaded', function() {
                                  var today = new Date();
                                  document.getElementById('birthday').value = formatDate(today);
                              });
                           </script>
                        </div>
                     </div>
                     <div class="ln_solid"></div>
                     <div class="item form-group">
                        <div class="col-md-6 col-sm-6 offset-md-3">
                           <button class="btn btn-primary" type="button">Cancel</button>
                           <button class="btn btn-primary" type="reset">Reset</button>
                           <button type="submit" class="btn btn-success">Submit</button>
                        </div>
                     </div>
                  </form>
               </div>
            </div>
         </div>
      </div>
   </div>
</div>
{% endblock %}

templates/footer.html
{% load static %}
<footer>
    <div class="pull-right">
      Gentelella - Bootstrap Admin Template by <a href="https://colorlib.com">Colorlib</a>
    </div>
    <div class="clearfix"></div>
  </footer>

templates/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <!-- Meta, title, CSS, favicons, etc. -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>Gentelella Alela! | </title>

    <!-- Bootstrap -->
    <link href="{% static 'vendors/bootstrap/dist/css/bootstrap.min.css' %}" rel="stylesheet">
    <!-- Font Awesome -->
    <link href="{% static 'vendors/font-awesome/css/font-awesome.min.css' %}" rel="stylesheet">
    <!-- NProgress -->
    <link href="{% static 'vendors/nprogress/nprogress.css' %}" rel="stylesheet">
    <!-- Animate.css -->
    <link href="{% static 'vendors/animate.css/animate.min.css' %}" rel="stylesheet">
    <!-- PNotify -->
    <link href="{% static 'vendors/pnotify/dist/pnotify.css' %}" rel="stylesheet">
    <link href="{% static 'vendors/pnotify/dist/pnotify.buttons.css' %}" rel="stylesheet">
    <link href="{% static 'vendors/pnotify/dist/pnotify.nonblock.css' %}" rel="stylesheet">
    <!-- Custom Theme Style -->
    <link href="{% static 'build/css/custom.min.css' %}" rel="stylesheet">
  </head>

  <body class="login">
    <div>
      <a class="hiddenanchor" id="signup"></a>
      <a class="hiddenanchor" id="signin"></a>

      <div class="login_wrapper">
        <div class="animate form login_form">
          <section class="login_content">
            <form method="post" action="{% url 'user_management:login' %}">
              {% csrf_token %}
              <h1>Login Form</h1>
              <div>
                <input type="text" class="form-control" name="username" placeholder="Username" required="" />
              </div>
              <div>
                <input type="password" class="form-control" name="password" placeholder="Password" required="" />
              </div>
              <div>
                <button type="submit"><a class="btn btn-default submit">Submit</a></button>
              </div>

              <div class="clearfix"></div>

              <div class="separator">
                <p class="change_link">New to site?
                  <a href="#signup" class="to_register"> Create Account </a>
                </p>

                <div class="clearfix"></div>
                <br />

                <div>
                  <h1><i class="fa fa-paw"></i>ERP!</h1>
                  <p>©2016 All Rights Reserved. JOSUN! is a Bootstrap 4 template. Privacy and Terms</p>
                </div>
              </div>
            </form>
          </section>
        </div>

        <div id="register" class="animate form registration_form">
          <section class="login_content">
            <form method="post" action="{% url 'user_management:register' %}">
              {% csrf_token %}
              <h1>Create Account</h1>
              <div>
                <input type="text" class="form-control" placeholder="Username" required="" name="username"/>
              </div>
              <div>
                <input type="email" class="form-control" placeholder="Email" required="" name="email"/>
              </div>
              <div>
                <input type="password" class="form-control" placeholder="Password" required="" name="password"/>
              </div>
              <div>
                <button type="submit"><a class="btn btn-default submit">Submit</a></button>
              </div>

              <div class="clearfix"></div>

              <div class="separator">
                <p class="change_link">Already a member ?
                  <a href="#signin" class="to_register"> Log in </a>
                </p>

                <div class="clearfix"></div>
                <br />

                <div>
                  <h1><i class="fa fa-paw"></i> ERP!</h1>
                  <p>©2016 All Rights Reserved. JOSUN! is a Bootstrap 4 template. Privacy and Terms</p>
                </div>
              </div>
            </form>
            {% if error %}
            <button id="alert_notification_3" class="btn btn-secondary source" style="display: none;"
            data-error-message="{{error}}"
            onclick="new PNotify({
              title: 'Error',
              text: '{{error}}',
              type: 'error',
              styling: 'bootstrap3',
              delay: 2000 
              });">Success</button>
              {% endif %}
          </section>
        </div>
      </div>
    </div>
    <!-- jQuery -->
    <script src="{% static 'vendors/jquery/dist/jquery.min.js' %}"></script>
    <!-- Bootstrap -->
    <script src="{% static 'vendors/bootstrap/dist/js/bootstrap.bundle.min.js' %}"></script>
    <!-- FastClick -->
    <script src="{% static 'vendors/fastclick/lib/fastclick.js' %}"></script>
    <!-- NProgress -->
    <script src="{% static 'vendors/nprogress/nprogress.js' %}"></script>
    <!-- iCheck -->
    <script src="{% static 'vendors/iCheck/icheck.min.js' %}"></script>
    
    <!-- PNotify -->
    <script src="{% static 'vendors/pnotify/dist/pnotify.js' %}"></script>
    <script src="{% static 'vendors/pnotify/dist/pnotify.buttons.js' %}"></script>
    <script src="{% static 'vendors/pnotify/dist/pnotify.nonblock.js' %}"></script>
    <!-- bootstrap-daterangepicker -->
    <script src="{% static 'vendors/moment/min/moment.min.js' %}"></script>
    <script src="{% static 'vendors/bootstrap-daterangepicker/daterangepicker.js' %}"></script>
    <!-- bootstrap-wysiwyg -->
    <script src="{% static 'vendors/bootstrap-wysiwyg/js/bootstrap-wysiwyg.min.js' %}"></script>
    <script src="{% static 'vendors/jquery.hotkeys/jquery.hotkeys.js' %}"></script>
    <script src="{% static 'vendors/google-code-prettify/src/prettify.js' %}"></script>
    <!-- jQuery Tags Input -->
    <script src="{% static 'vendors/jquery.tagsinput/src/jquery.tagsinput.js' %}"></script>
    <!-- Switchery -->
    <script src="{% static 'vendors/switchery/dist/switchery.min.js' %}"></script>
    <!-- Select2 -->
    <script src="{% static 'vendors/select2/dist/js/select2.full.min.js' %}"></script>
    <!-- Parsley -->
    <script src="{% static 'vendors/parsleyjs/dist/parsley.min.js' %}"></script>
    <!-- Autosize -->
    <script src="{% static 'vendors/autosize/dist/autosize.min.js' %}"></script>
    <!-- jQuery autocomplete -->
    <script src="{% static 'vendors/devbridge-autocomplete/dist/jquery.autocomplete.min.js' %}"></script>
    <!-- starrr -->
    <script src="{% static 'vendors/starrr/dist/starrr.js' %}"></script>
    <!-- Custom Theme Scripts -->
    <script src="{% static 'build/js/custom.min.js' %}"></script>
    <script>
      
      var error = $('#alert_notification_3').data('error-message');
      if (error) {
        $('#alert_notification_3').click();
      }
    </script>
  </body>
</html>

templates/pagination.html
  <nav aria-label="Page navigation">
    <ul class="pagination justify-content-center">
      {% if page_obj.has_previous %}
        <li class="page-item">
          <a class="page-link" href="?page=1" aria-label="First">
            <span aria-hidden="true">&laquo;&laquo;</span>
          </a>
        </li>
        <li class="page-item">
          <a class="page-link" href="?page={{ page_obj.previous_page_number }}" aria-label="Previous">
            <span aria-hidden="true">&laquo;</span>
          </a>
        </li>
      {% endif %}

      <li class="page-item disabled">
        <span class="page-link">Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}</span>
      </li>

      {% if page_obj.has_next %}
        <li class="page-item">
          <a class="page-link" href="?page={{ page_obj.next_page_number }}" aria-label="Next">
            <span aria-hidden="true">&raquo;</span>
          </a>
        </li>
        <li class="page-item">
          <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}" aria-label="Last">
            <span aria-hidden="true">&raquo;&raquo;</span>
          </a>
        </li>
      {% endif %}
    </ul>
  </nav>

templates/product_list.html
{% extends 'base.html' %}
{% block content %}
<div class="right_col" role="main">
   <div class="">
      <div class="page-title">
         <div class="title_left">
            <h3>Product Master <small>List of products</small></h3>
            <a href="{% url 'product_master:create_view'%}" class="btn btn-primary btn-xs"><i class="fa fa-plus"></i>Create</a>
         </div>
      </div>
      <div class="clearfix"></div>
      <div class="row">
         <div class="col-md-12 col-sm-12 ">
            <div class="x_panel">
               <div class="x_content">
                  <h1>Search Results</h1>
                     <form method="get" action="{% url 'product_master:list_view' %}" class="mb-3">
                        <input type="text" name="query" value="{{ query }}" class="form-control" placeholder="Search for products...">
                        <button type="submit" class="btn btn-primary mt-2">Search</button>
                     </form>
                  <div class="row">
                     <div class="col-sm-12">
                        <div class="card-box table-responsive">
                           <table  class="table table-striped table-bordered" style="width:100%">
                              <!-- <table id="datatable-buttons" class="table table-striped table-bordered" style="width:100%"> -->

                              <thead>
                                 <tr>
                                    <th>Name</th>
                                    <th>Quantity</th>
                                    <th>Description</th>
                                    <th>Price</th>
                                    <th>Created date</th>
                                    <th style="width: 310px;">Action</th>
                                 </tr>
                              </thead>
                              <tbody>
                                 {% for prod in products %}
                                 <tr id="prod_row_{{ prod.id }}">
                                    <td id="prod_name_{{ prod.id }}">{{ prod.name }}</td>
                                    <td id="prod_quantity_{{ prod.id }}">{{ prod.quantity }}</td>
                                    <td id="prod_desc_{{ prod.id }}">{{ prod.desc }}</td>
                                    <td id="prod_price_{{ prod.id }}">{{ prod.price }}</td>
                                    <td id="prod_published_date_{{ prod.id }}">{{ prod.published_date }}</td>
                                    <td>
                                       <a href="#" class="btn btn-round btn-info btn-xs edit-btn" data-prod-id="{{ prod.id }}"><i class="fa fa-pencil"></i> Edit </a>
                                       <a href="#" class="btn btn-round bg-green btn-xs view-btn" data-prod-id="{{ prod.id }}"><i class="fa fa-eye"></i> View </a>
                                       <a href="#" class="btn btn-round btn-danger btn-xs del-btn" data-prod-name= "{{ prod.name }}" data-prod-id="{{ prod.id }}"><i class="fa fa-trash-o"></i> Delete </a>
                                    </td>
                                 </tr>
                                 {% empty %}
                                 <tr>
                                    <td colspan="6">No products found.</td>
                                 </tr>
                                 {% endfor %}
                              </tbody>
                           </table>
                           {% include 'pagination.html' %}
                        </div>
                     </div>
                  </div>
               </div>
            </div>
         </div>
      </div>
      <!-- Small Modal -->
      <div class="modal fade bs-example-modal-sm" id="confirmDeleteModal" tabindex="-1" role="dialog" aria-labelledby="confirmDeleteModalLabel" aria-hidden="true">
        <div class="modal-dialog modal-sm">
          <div class="modal-content">
 
            <div class="modal-header">
              <h4 class="modal-title" id="myModalLabel2">Modal title</h4>
            </div>
            <div class="modal-body">
              <h4>Are you sure you want to delete ?</h4>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
                <button type="button" class="btn btn-primary" id="confirmDeleteBtn">Yes, Delete</button>
            </div>
 
          </div>
        </div>
      </div>
      <!-- Large modal -->
      <button style="display: none;" type="button" class="btn btn-primary" data-toggle="modal" id="view_modal" data-target=".view_product_modal">Large modal</button>
      <div class="modal fade view_product_modal" tabindex="-1" role="dialog" aria-hidden="true">
         <div class="modal-dialog modal-lg">
            <div class="modal-content">
               <div class="modal-header">
                  <h4 class="modal-title" id="myModalLabel">Product View</h4>
                  <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">×</span>
                  </button>
               </div>
               <div class="modal-body">
                  <h4 id="cat_prod"></h4>
                  <div class="form-group row">
                     <label class="control-label col-md-3 col-sm-3 ">Name</label>
                     <div class="col-md-9 col-sm-9 ">
                        <input type="text" id="name_prod" class="form-control" readonly="readonly">
                     </div>
                  </div>
                  <div class="form-group row">
                     <label class="control-label col-md-3 col-sm-3 ">Quantity</label>
                     <div class="col-md-9 col-sm-9 ">
                        <input type="text" id="qty_prod" class="form-control" readonly="readonly">
                     </div>
                  </div>
                  <div class="form-group row">
                     <label class="control-label col-md-3 col-sm-3 ">Description</label>
                     <div class="col-md-9 col-sm-9 ">
                        <input type="text" id="desc_prod" class="form-control" readonly="readonly">
                     </div>
                  </div>
                  <div class="form-group row">
                     <label class="control-label col-md-3 col-sm-3 ">Price</label>
                     <div class="col-md-9 col-sm-9 ">
                        <input type="text" id="price_prod" class="form-control" readonly="readonly">
                     </div>
                  </div>
                  <div class="form-group row">
                     <label class="control-label col-md-3 col-sm-3 ">published date</label>
                     <div class="col-md-9 col-sm-9 ">
                        <input type="text" id="date_prod" class="form-control" readonly="readonly">
                     </div>
                  </div>
               </div>
               <div class="modal-footer">
                  <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
               </div>
            </div>
         </div>
      </div>
      <button style="display: none;" id='alert_notification_2' class="btn btn-secondary source" onclick="new PNotify({
        title: 'Deleted',
        text: 'Deleted successfully',
        type: 'success',
        styling: 'bootstrap3',
        delay: 2000 
        });">Success</button>
      <button style="display: none;" id='alert_notification' class="btn btn-secondary source" onclick="new PNotify({
         title: 'Edited',
         text: 'Updated data successfully done',
         type: 'success',
         styling: 'bootstrap3',
         delay: 2000 
         });">Success</button>
   </div>
</div>
{% endblock %}

templates/report.html
{% extends 'base.html' %}
{% block content %}
<div class="right_col" role="main">
   <div class="">
      <div class="page-title">
         <div class="title_left">
            <h3>Generate Report</h3>
         </div>
      </div>
      <div class="clearfix"></div>
      <div class="row">
         <div class="col-md-12 col-sm-12 ">
            <div class="x_panel">
               <div class="x_content">
                  <div class="row">
                     <div class="col-md-12 col-sm-12 ">
                        <div class="x_panel">
                           <div class="x_content">
                              <br />
                              <form class="form-label-left input_mask" method="post" action="{% url 'product_master:reports_view' %}">
                                 {% csrf_token %}
                                 <div class="col-md-6 col-sm-6  form-group has-feedback">
                                    <label class="col-form-label col-md-3 col-sm-3 label-align">Select <span class="required">*</span></label>
                                    <div class="col-md-6 col-sm-6 ">
                                  
                                        <select class="form-control" required="required" name="category_id">
                                        {% for cat in category %}
                                        <option value="{{cat.id}}" {% if cat.id == selected_cat %} selected {% endif %}>{{cat.Category}}</option>
                                        {% endfor %}
                                        </select>

                                    </div>
                                 </div>
                                 <div class="col-md-6 col-sm-6  form-group has-feedback">
                                    <label class="col-form-label col-md-3 col-sm-3 ">Published Date<span class="required">*</span>
                                    </label>
                                    <div class="col-md-9 col-sm-9 ">
                                       <input id="birthday" {% if date %} value="{{date}}" {% endif %} name="created_date" class="date-picker form-control" placeholder="dd-mm-yyyy" type="text" required="required" type="text" onfocus="this.type='date'" onmouseover="this.type='date'" onclick="this.type='date'" onblur="this.type='text'">
                                    </div>
                                 </div>
                                 <div class="col-md-9 col-sm-9  offset-md-3 text-right">
                                    <button class="btn btn-primary" type="reset">Reset</button>
                                    <button type="submit" class="btn btn-success">Submit</button>
                                 </div>
                              </form>
                           </div>
                        </div>
                     </div>
                  </div>
                  <div class="row">
                     {% if products or date %}
                     <div class="col-md-12 col-sm-12 ">
                        <div class="x_panel">
                           <div class="x_content">
                              <br />
                              <div class="col-md-12 col-sm-12  ">
                                 <div class="x_panel">
                                    <div class="x_content">
                                       <div class="table-responsive">
                                          <table class="table table-striped jambo_table bulk_action">
                                             <thead>
                                                <tr class="headings">
                                                   <th class="column-title">Name </th>
                                                   <th class="column-title">Quantity </th>
                                                   <th class="column-title">Description</th>
                                                   <th class="column-title">price </th>
                                                   <th class="column-title">Published Date </th>
                                                </tr>
                                             </thead>
                                             <tbody>
                                                {% for prod in products %}
                                                <tr class="even pointer">
                                                   <td class=" ">{{prod.name}}</td>
                                                   <td class=" ">{{prod.quantity}}</td>
                                                   <td class=" ">{{prod.desc}}</td>
                                                   <td class=" ">{{prod.price}}</td>
                                                   <td class=" ">{{prod.published_date}}</td>
                                                   </td>
                                                </tr>
                                                {% empty %}
                                                <tr>
                                                    <td colspan="5" align="center">No data..</td>
                                                </tr>
                                                {% endfor %}
                                             </tbody>
                                          </table>
                                       </div>
                                    </div>
                                 </div>
                              </div>
                           </div>
                        </div>
                     </div>
                     {% endif%}
                  </div>
               </div>
            </div>
         </div>
      </div>
   </div>
</div>
{% endblock %}

templates/sidenavbar.html
{% load static %}
<div class="col-md-3 left_col">
   <div class="left_col scroll-view">
      <div class="navbar nav_title" style="border: 0;">
         <a href="index.html" class="site_title"><i class="fa fa-paw"></i> <span>JOSUN!</span></a>
      </div>
      <div class="clearfix"></div>
      <!-- menu profile quick info -->
      <div class="profile clearfix">
         <div class="profile_pic">
            <img src="{% static 'images/img.jpg' %}" alt="..." class="img-circle profile_img">
         </div>
         <div class="profile_info">
            <span>Welcome,</span>
            <h2>{{request.user}}</h2>
         </div>
      </div>
      <!-- /menu profile quick info -->
      <br />
      <!-- sidebar menu -->
      <div id="sidebar-menu" class="main_menu_side hidden-print main_menu">
         <div class="menu_section">
            <h3>General</h3>
            <ul class="nav side-menu">
               <li>
                  <a><i class="fa fa-cube"></i>Product Master <span class="fa fa-chevron-down"></span></a>
                  <ul class="nav child_menu">
                     <li><a href="{% url 'product_master:list_view'%}">Product List</a></li>
                     <li><a href="{% url 'product_master:create_view'%}">Add Product</a></li>
                     <li><a href="{% url 'product_master:reports_view'%}">Reports</a></li>
                  </ul>
               </li>
            </ul>
         </div>
      </div>
      <!-- /sidebar menu -->
      <!-- /menu footer buttons -->
      <div class="sidebar-footer hidden-small">
         <a data-toggle="tooltip" data-placement="top" title="Settings">
         <span class="glyphicon glyphicon-cog" aria-hidden="true"></span>
         </a>
         <a id="fullscreenButton" data-toggle="tooltip" data-placement="top" title="FullScreen">
         <span class="glyphicon glyphicon-fullscreen" aria-hidden="true"></span>
         </a>
         <a data-toggle="tooltip" data-placement="top" title="Lock">
         <span class="glyphicon glyphicon-eye-close" aria-hidden="true"></span>
         </a>
         <a data-toggle="tooltip" data-placement="top" title="Logout" href="{% url 'user_management:logout'%}">
         <span class="glyphicon glyphicon-off" aria-hidden="true"></span>
         </a>
      </div>
      <!-- /menu footer buttons -->
   </div>
</div>